### ISSUE TITLE
Publishing Checklist

### ISSUE THREAD

**Issue by Flaque** [Flaque/quirk#9]
# Overview

These are all the things that we need to do in order to publish. We're publishing first on iOS.

## High Value Steps
These are required to publish for iOS.
- [x] Determine price. [Based on survey data](https://docs.google.com/spreadsheets/d/1HG-pWdF2AvbKuMf3uziIwYMkns-l40e27D961Wrg70w/edit?usp=sharing), it should probably be $2 dollars. ($2 sounds good, lower the price if needed).
- [x] Make a splash screen
- [x] Create [an Icon](https://docs.expo.io/versions/latest/guides/app-icons.html)
- [x] Configure [bundle identifier](https://docs.expo.io/versions/latest/guides/configuration.html#bundleidentifier)
- [x] [Get a privacy policy](https://app-privacy-policy-generator.firebaseapp.com/)

## Low Value Steps
These we should do, but aren't required to publish for iOS. 
- [ ] Make sure the app doesn't "break" on iPads
- [ ] Configure the status bar so we're not clashing
- [ ] Choose a [PrimaryColor (Android)](https://docs.expo.io/versions/latest/guides/configuration.html#primarycolor)

**Comment by Flaque** [comment]
Published
